MATCH_TYPES = {
    "ms": "Men's Singles",
    "md": "Men's Doubles",
    "ws": "Women's Singles",
    "wd": "Women's Doubles",
    "xd": "Mixed Doubles",
}

FIXED_TAGS = "#sunbadminton #badminton #cafebadminton"
CATEGORY_SPORTS = "17"
DATE_FORMAT = "%d %b %Y"  # Example: 25 Dec 2024
TEMPORAL_TASK_QUEUE = "badminton-video-processing"

# Workflow stages
WORKFLOW_STAGE_INITIALIZING = "INITIALIZING"
WORKFLOW_STAGE_CREATING_METADATA = "CREATING_METADATA"
WORKFLOW_STAGE_EXTRACTING_FRAMES = "EXTRACTING_FRAMES"
WORKFLOW_STAGE_RANKING_CANDIDATES = "RANKING_CANDIDATES"
WORKFLOW_STAGE_WAITING_FOR_SELECTION = "WAITING_FOR_SELECTION"
WORKFLOW_STAGE_SELECTED = "SELECTED"
WORKFLOW_STAGE_ENHANCING_THUMBNAIL = "ENHANCING_THUMBNAIL"
WORKFLOW_STAGE_UPLOADING = "UPLOADING"
WORKFLOW_STAGE_SETTING_THUMBNAIL = "SETTING_THUMBNAIL"
WORKFLOW_STAGE_COMPLETED = "COMPLETED"
